version: '3.1'

services:
  flwrspot:
    build: .
    ports:
      - 8080:8080
    environment:
      - FLYWAY_PASS=${PSQL_ROOT_PASSWORD}
      - PSQL_URL=jdbc:postgresql://postgres:5432/flwrspot
  postgres:
    image: postgres:9.6.21-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${PSQL_ROOT_PASSWORD}
    volumes:
      - ./sql/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    ports:
      - 5432:5432
