spring:
  application:
    name: Flwrspot API Service Monolith
  datasource:
    url: ${PSQL_URL:jdbc:postgresql://localhost:5432/flwrspot}
    username: ${PSQL_USER:flwrspot}
    password: ${PSQL_PASS:flwrspot}
    hikari:
      pool-name: flwrspot-knowledge-base-pool
  flyway:
    user: ${FLYWAY_USER:postgres}
    password: ${FLYWAY_PASS:}
    placeholders.db.user: ${spring.datasource.username}
    ignore-future-migrations: false
    validate-migration-naming: true
  jpa:
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
      hibernate.criteria.literal_handling_mode: inline
      hibernate.show_sql: false
      hibernate.generate_statistics: false
app:
  jwtSecret: flwrspotjwt
  jwtExpirationMs: 600000000
quotes:
  api-url: https://quotes.rest
